version: 0.0
os: linux
files:
  - source: ProductManipulation.war
    destination: /opt/tomcat/apache-tomcat-9.0.75/webapps/
hooks:
  AfterInstall:
    - location: scripts/restart_tomcat.sh
      timeout: 300
      runas: root
